# kate: indent-width 2;

clone_depth: 1

environment:
  matrix:
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-desktop-msvc2015
  - TARGET: desktop
    COMPILER: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-desktop-msvc2017
  - TARGET: desktop
    COMPILER: mingw
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-desktop-mingw
  - TARGET: desktop-gles
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-es2-msvc2015
  - TARGET: desktop-gles
    TARGET_GLES2: ON
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-es2-msvc2017
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    APPVEYOR_JOB_NAME: windows-es3-msvc2015
  - TARGET: desktop-gles
    TARGET_GLES2: OFF
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    APPVEYOR_JOB_NAME: windows-es3-msvc2017
  #- TARGET: rt
    #TARGET_GLES2: ON
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #APPVEYOR_JOB_NAME: windows-rt-es2-msvc2015
  #- TARGET: rt
    #TARGET_GLES2: ON
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #APPVEYOR_JOB_NAME: windows-rt-es2-msvc2017
  #- TARGET: rt
    #TARGET_GLES2: OFF
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    #APPVEYOR_JOB_NAME: windows-rt-es3-msvc2015
  #- TARGET: rt
    #TARGET_GLES2: OFF
    #APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #APPVEYOR_JOB_NAME: windows-rt-es3-msvc2017

notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/415ae90928ba0dbd3df4
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true

install:
- cinst ninja
- set PATH=C:/Sys/bin;C:/tools/ninja;%PATH%
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" pip install codecov

# OVR SDK
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" IF NOT EXIST %APPVEYOR_BUILD_FOLDER%\ovr_sdk_win_1.4.0_public.zip appveyor DownloadFile https://static.oculus.com/sdk-downloads/1.4.0/Public/1463687419/ovr_sdk_win_1.4.0_public.zip
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" 7z x ovr_sdk_win_1.4.0_public.zip -o%APPVEYOR_BUILD_FOLDER%\deps

build_script:
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "msvc" call package\ci\appveyor-desktop.bat
- IF "%TARGET%" == "desktop" IF "%COMPILER%" == "mingw" call package\ci\appveyor-desktop-mingw.bat
- IF "%TARGET%" == "desktop-gles" call package\ci\appveyor-desktop-gles.bat
- IF "%TARGET%" == "rt" call package\ci\appveyor-rt.bat

cache:
- ovr_sdk_win_1.4.0_public.zip -> package/ci/appveyor-cache-reset.txt
- 2.86.1.zip -> package/ci/appveyor-cache-reset.txt
